server:
  port: 8080
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:sqlserver://LOCALHOST\SQLEXPRESS;databaseName=ife;TrustServerCertificate=True;
    username: sa
    password: sa
  jpa:
    show-sql: true